import { requireSession } from "../auth/guards.js";
import { bindLogout } from "../auth/logout.js?v=20260812-nav";
import { generateInsight, insightContent, listInsights, listStudyActions, updateStudyAction } from "../services/insight.service.js";
import { getCurrentSemester } from "../services/semester.service.js";
import { el } from "../utils/dom.js";
import { setBusy, showMessage } from "../utils/forms.js";

await requireSession({ requireOnboarding: true }); bindLogout(); const semester = await getCurrentSemester();
const insightList = document.querySelector("#insight-list"); const actionList = document.querySelector("#action-list"); const generate = document.querySelector("#generate-insight"); let insights = []; let actions = []; let activeFilter = "all";
document.querySelector("#insight-semester").textContent = `${semester.academic_year} · ${semester.semester_name}`;
const formatDate = (value) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric" }).format(new Date(value));
const typeLabel = (value) => value === "semester_review" ? "Semester review" : value === "course_focus" ? "Course focus" : "Current summary";
function renderInsight(insight, index) { const content = insightContent(insight); const observations = el("ul", { className: "observation-list" }); for (const observation of content.observations ?? []) observations.append(el("li", {}, [el("span", { text: String(observations.children.length + 1).padStart(2, "0") }), el("p", { text: observation })])); return el("article", { className: `insight-card${index === 0 ? " latest" : ""}` }, [el("header", {}, [el("div", { className: "insight-meta" }, [el("span", { text: typeLabel(insight.insight_type) }), el("time", { datetime: insight.generated_at, text: formatDate(insight.generated_at) })]), index === 0 ? el("span", { className: "latest-badge", text: "Latest" }) : el("span", { className: "ai-badge", text: "AI explanation" })]), el("h2", { text: content.title || insight.title }), el("p", { className: "insight-summary", text: content.summary || insight.summary }), observations, el("footer", {}, [el("span", { text: "Based on calculated EduPulse context" }), el("small", { text: insight.prompt_version })])]); }
function renderInsights() { insightList.replaceChildren(); insightList.setAttribute("aria-busy", "false"); const filtered = insights.filter((item) => activeFilter === "all" || item.insight_type === activeFilter); document.querySelector("#insight-count-copy").textContent = insights.length ? `${insights.length} saved ${insights.length === 1 ? "explanation" : "explanations"}, newest first.` : "Generate an explanation after recording academic evidence."; if (!filtered.length) { const empty = el("div", { className: "insight-empty" }, [el("span", { text: activeFilter === "all" ? "✦" : "⌕" }), el("h3", { text: activeFilter === "all" ? "Your first explanation starts here." : "No insights in this view." }), el("p", { text: activeFilter === "all" ? "Add academic evidence, then generate an insight grounded in your current semester." : "Choose All to return to the complete explanation history." })]); if (activeFilter !== "all") { const reset = el("button", { className: "button secondary", type: "button", text: "Show all" }); reset.addEventListener("click", () => setFilter("all")); empty.append(reset); } insightList.append(empty); return; } insightList.append(...filtered.map(renderInsight)); }
function renderActions() { actionList.replaceChildren(); const pending = actions.filter((item) => item.status === "pending"); const completed = actions.filter((item) => item.status === "completed").length; const rate = actions.length ? completed / actions.length * 100 : 0; document.querySelector("#pending-action-count").textContent = pending.length; document.querySelector("#action-progress-label").textContent = actions.length ? `${completed}/${actions.length} complete` : "No actions"; document.querySelector("#action-progress-bar").style.width = `${rate}%`; if (!actions.length) return actionList.append(el("div", { className: "action-empty" }, [el("span", { text: "✓" }), el("p", { text: "Recommended study actions will appear with your generated insights." })])); for (const action of actions) { const priority = action.priority === 1 ? "High" : action.priority === 2 ? "Medium" : "Steady"; const row = el("article", { className: `action-row ${action.status}` }, [el("span", { className: `priority priority-${action.priority}`, text: String(action.priority) }), el("div", {}, [el("div", { className: "action-title-row" }, [el("strong", { text: action.title }), el("small", { text: priority })]), el("p", { text: action.description ?? "A focused next step from your academic context." })])]); const button = el("button", { className: "action-toggle", type: "button", "aria-label": `${action.status === "completed" ? "Reopen" : "Complete"} ${action.title}`, text: action.status === "completed" ? "↺" : "✓" }); button.addEventListener("click", async () => { button.disabled = true; try { await updateStudyAction(action.id, action.status === "completed" ? "pending" : "completed"); await loadData(); } catch (error) { showMessage(error.message || "The action could not be updated.", "error"); button.disabled = false; } }); row.append(button); actionList.append(row); } }
function setFilter(filter) { activeFilter = filter; document.querySelectorAll("[data-insight-filter]").forEach((button) => { const active = button.dataset.insightFilter === filter; button.classList.toggle("active", active); button.setAttribute("aria-pressed", String(active)); }); renderInsights(); }
async function loadData() { [insights, actions] = await Promise.all([listInsights(semester.id), listStudyActions(semester.id)]); renderInsights(); renderActions(); }
document.querySelector(".insight-filter").addEventListener("click", (event) => { const button = event.target.closest("[data-insight-filter]"); if (button) setFilter(button.dataset.insightFilter); });
generate.addEventListener("click", async () => { setBusy(generate, true, "Generating…"); try { const result = await generateInsight("home_summary"); showMessage(result.cached ? "Your current insight is still up to date." : "A new insight was generated from your academic data.", "success"); await loadData(); } catch (error) { showMessage(error.message || "Insight generation failed. Try again shortly.", "error"); } finally { setBusy(generate, false); } });
await loadData();
