import { requireSession } from "../auth/guards.js";
import { bindLogout } from "../auth/logout.js?v=20260812-nav";
import { listGradingScales } from "../services/grading.service.js";
import { createSemester, listSemesters, setCurrentSemester, updateSemester } from "../services/semester.service.js";
import { el } from "../utils/dom.js";
import { setBusy, showMessage, userMessage } from "../utils/forms.js";

const session = await requireSession({ requireOnboarding: true }); bindLogout();
const form = document.querySelector("#semester-form"); const dialog = document.querySelector("#semester-dialog"); const list = document.querySelector("#semester-list"); const toast = document.querySelector("#semester-toast"); let scales = []; let toastTimer;
const formatDate = (value) => value ? new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric" }).format(new Date(`${value}T00:00:00`)) : null;
function announce(message) { clearTimeout(toastTimer); toast.textContent = message; toast.hidden = false; toastTimer = setTimeout(() => { toast.hidden = true; }, 3200); }
function scaleFor(id) { return scales.find((scale) => scale.id === id); }
function updateGpaHelp() { const scale = scaleFor(form.elements.grading_scale_id.value); document.querySelector("#target-gpa-help").textContent = scale ? `Maximum for ${scale.name}: ${Number(scale.max_gpa).toFixed(2).replace(/\.00$/, "")}` : "Must fit the selected scale."; form.elements.target_gpa.max = scale?.max_gpa ?? ""; }
function openForm() { form.reset(); document.querySelector("#form-message").hidden = true; updateGpaHelp(); dialog.showModal(); requestAnimationFrame(() => form.elements.academic_year.focus()); }
function statusLabel(value) { return value === "completed" ? "Completed" : value === "archived" ? "Archived" : "Active"; }
function createSemesterCard(semester, index) {
  const scale = scaleFor(semester.grading_scale_id); const dateRange = semester.start_date || semester.end_date ? `${formatDate(semester.start_date) ?? "Start not set"} — ${formatDate(semester.end_date) ?? "Ongoing"}` : "Dates not configured";
  const facts = el("dl", { className: "semester-facts" }, [el("div", {}, [el("dt", { text: "Grading scale" }), el("dd", { text: scale?.name ?? "Assigned scale" })]), el("div", {}, [el("dt", { text: "Target average" }), el("dd", { text: semester.target_average == null ? "Not set" : `${Number(semester.target_average)}%` })]), el("div", {}, [el("dt", { text: "Target GPA" }), el("dd", { text: semester.target_gpa == null ? "Not set" : Number(semester.target_gpa).toFixed(2).replace(/\.00$/, "") })])]);
  const actions = el("div", { className: "semester-actions" });
  if (!semester.is_current) { const activate = el("button", { className: "button secondary", type: "button", text: "Make current" }); activate.addEventListener("click", async () => { setBusy(activate, true, "Activating…"); try { await setCurrentSemester(semester.id); announce(`${semester.semester_name} is now current`); await render(); } catch (error) { announce(userMessage(error, "We couldn’t activate that semester. Please try again.")); setBusy(activate, false); } }); actions.append(activate); }
  if (semester.status === "active") { const finish = el("button", { className: "text-button", type: "button", text: "Mark completed" }); finish.addEventListener("click", async () => { finish.disabled = true; try { await updateSemester(semester.id, { status: "completed" }); announce(`${semester.semester_name} marked completed`); await render(); } catch (error) { announce(userMessage(error, "We couldn’t update that semester. Please try again.")); finish.disabled = false; } }); actions.append(finish); }
  return el("article", { className: `semester-card${semester.is_current ? " current" : ""}` }, [el("div", { className: "semester-index", text: String(index + 1).padStart(2, "0") }), el("div", { className: "semester-card-main" }, [el("div", { className: "semester-card-top" }, [el("div", {}, [el("span", { className: `semester-status ${semester.status}`, text: statusLabel(semester.status) }), el("h2", { text: semester.semester_name }), el("p", { text: `${semester.academic_year} · ${dateRange}` })]), semester.is_current ? el("span", { className: "current-badge", text: "Current semester" }) : el("span", { className: "history-badge", text: "History" })]), facts, actions])]);
}
async function render() { const semesters = await listSemesters(); list.replaceChildren(); list.setAttribute("aria-busy", "false"); document.querySelector("#semester-total").textContent = semesters.length; document.querySelector("#semester-list-copy").textContent = semesters.length ? `${semesters.length} academic ${semesters.length === 1 ? "period" : "periods"}, newest first.` : "No academic periods created yet."; const current = semesters.find((item) => item.is_current); document.querySelector("#current-semester-name").textContent = current ? `${current.academic_year} · ${current.semester_name}` : "No current semester"; document.querySelector("#current-semester-copy").textContent = current ? "The dashboard and new courses currently follow this academic period." : "Create a semester to establish the dashboard context."; if (!semesters.length) { const empty = el("div", { className: "semester-empty" }, [el("span", { text: "+" }), el("h2", { text: "Create your first academic period." }), el("p", { text: "A semester keeps its courses, targets and trends together." })]); const button = el("button", { className: "button", type: "button", text: "Create semester" }); button.addEventListener("click", openForm); empty.append(button); list.append(empty); return; } list.append(...semesters.map(createSemesterCard)); }
scales = await listGradingScales(); for (const scale of scales) form.elements.grading_scale_id.append(el("option", { value: scale.id, text: `${scale.name} · ${scale.max_gpa} max GPA` })); updateGpaHelp();
document.querySelector("#add-semester").addEventListener("click", openForm); document.querySelector("#close-semester-dialog").addEventListener("click", () => dialog.close()); document.querySelector("#cancel-semester-form").addEventListener("click", () => dialog.close()); form.elements.grading_scale_id.addEventListener("change", updateGpaHelp);
form.addEventListener("submit", async (event) => { event.preventDefault(); const submit = form.querySelector("button[type=submit]"); const values = Object.fromEntries(new FormData(form)); for (const key of ["start_date", "end_date"]) values[key] ||= null; values.target_average = values.target_average ? Number(values.target_average) : null; values.target_gpa = values.target_gpa ? Number(values.target_gpa) : null; values.status = "active"; if (values.start_date && values.end_date && values.end_date < values.start_date) return showMessage("End date cannot be earlier than start date.", "error"); setBusy(submit, true, "Creating…"); try { const semester = await createSemester(values, session.user.id); await setCurrentSemester(semester.id); dialog.close(); announce(`${semester.semester_name} created and activated`); await render(); } catch (error) { showMessage(userMessage(error, "We couldn’t create this semester. Check the details and try again."), "error"); } finally { setBusy(submit, false); } });
await render();
