import { requireSession } from "../auth/guards.js";
import { bindLogout } from "../auth/logout.js?v=20260812-nav";
import { listGradingScales } from "../services/grading.service.js";
import { createSemester, listSemesters, setCurrentSemester, updateSemester } from "../services/semester.service.js";
import { el } from "../utils/dom.js";
import { setBusy, showMessage } from "../utils/forms.js";
const session = await requireSession({ requireOnboarding: true }); bindLogout(); const form = document.querySelector("#semester-form"); const dialog = document.querySelector("#semester-dialog");
const scales = await listGradingScales(); for (const scale of scales) form.elements.grading_scale_id.append(el("option", { value: scale.id, text: `${scale.name} (${scale.max_gpa})` }));
document.querySelector("#add-semester").addEventListener("click", () => { form.reset(); document.querySelector("#semester-dialog-title").textContent = "Create semester"; dialog.showModal(); }); document.querySelector("#close-semester-dialog").addEventListener("click", () => dialog.close());
async function render() { const semesters = await listSemesters(); const list = document.querySelector("#semester-list"); list.replaceChildren(); for (const semester of semesters) { const card = el("article", { className: `semester-row card ${semester.is_current ? "current" : ""}` }, [el("div", {}, [el("span", { className: "eyebrow", text: semester.status }), el("h2", { text: semester.semester_name }), el("p", { className: "muted", text: `${semester.academic_year}${semester.start_date ? ` · ${semester.start_date}` : ""}` })]), el("strong", { text: semester.is_current ? "Current" : "Historical" })]); const actions = el("div", { className: "row-actions" }); if (!semester.is_current) { const activate = el("button", { className: "text-button", type: "button", text: "Make current" }); activate.addEventListener("click", async () => { await setCurrentSemester(semester.id); await render(); }); actions.append(activate); } if (semester.status === "active") { const finish = el("button", { className: "text-button", type: "button", text: "Mark completed" }); finish.addEventListener("click", async () => { await updateSemester(semester.id, { status: "completed" }); await render(); }); actions.append(finish); } card.append(actions); list.append(card); } }
form.addEventListener("submit", async (event) => { event.preventDefault(); const submit = form.querySelector("button[type=submit]"); const values = Object.fromEntries(new FormData(form)); for (const key of ["start_date", "end_date"]) values[key] ||= null; values.target_average = values.target_average ? Number(values.target_average) : null; values.target_gpa = values.target_gpa ? Number(values.target_gpa) : null; values.status = "active"; setBusy(submit, true, "Creating…"); try { const semester = await createSemester(values, session.user.id); await setCurrentSemester(semester.id); dialog.close(); await render(); } catch (error) { showMessage(error.message, "error"); } finally { setBusy(submit, false); } }); await render();
